# Jekyll configuration for GitHub Pages

theme: minima

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
title: My desire to grow
description: The only thing you can be sure of is change. At the same time we expect ourselves to follow our old roots, that don't serve us anymore, just out of habit. I was there for sure. Now is the time I welcome the New, with my arms open. 
